### ISSUE TITLE
zappa command requires virtualenv

### ISSUE THREAD

**Issue by lc0rp** [danielwhatmuff/zappa#1]
Like this image!

Wasn't able to get the zappa command to work. It kept failing with the error "zappa requires a virtualenv"

I eventually changed the zappashell command to this:

```
alias zappashell='docker run -ti -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION -v $(pwd):/var/task  --rm zappa bash -c "source /var/venv/bin/activate; bash"'
```

And then I was able to run ```zappa deploy``` within the zappa shell

**Comment by danielwhatmuff** [comment]
Glad you like it. Have added note to the readme about sourcing a virtualenv. Cheers.
