### ISSUE TITLE
Python upgrade from 2.7 to 3.6

### ISSUE THREAD

**Issue by avish-3pg** [danielwhatmuff/zappa#5]
@danielwhatmuff  please advice if we are going with the pull request for python upgrade from 2.7 to 3.6 from this commit https://github.com/iMerica/zappa-docker/commit/c351bd60effdbdb9d7e01bc3bfdb361333345bd5
 by @imerica ? 

I was hoping to leverage this update with bitbucket pipeline at the earliest. Please advice? Thank you.

**Comment by iMerica** [comment]
I'm happy to submit that PR and delete my fork if @danielwhatmuff is on board with upgrading. I only forked this repo because I had an urgent need for 3.6.

**Comment by avish-3pg** [comment]
Thank you @iMerica . Also, what is the name of the published docker image (if we have) like for example for the one @danielwhatmuff created it is danielwhatmuff/zappa, so is there an published image with 3.6? Please advice.

**Comment by danielwhatmuff** [comment]
Sure, @iMerica a PR for v3 would be cool. Ill then push a build to Docker hub with a new image tag.

**Comment by james-burke-codes** [comment]
So I guess this hasn't been deployed to docker hub yet?

**Comment by aarcro** [comment]
Am I missing something here? I don't see python36u available

```
docker run -it --rm -v ${HOME}/.aws:/root/.aws -v $(pwd):/var/task danielwhatmuff/zappa bash
zappa> yum clean all
zappa> yum install python36u
No package python36u available.
zappa> yum search python3
===================================================================================== N/S matched: python3 ======================================================================================
mod24_wsgi-python34.x86_64 : A WSGI interface for Python web applications in Apache
postgresql92-plpython27.x86_64 : The Python3 procedural language for PostgreSQL
python34.x86_64 : Version 3.4 of the Python programming language aka Python 3000
python34-devel.x86_64 : Libraries and header files needed for Python 3.4 development
python34-docs.noarch : Documentation for the Python programming language
python34-libs.i686 : Python 3.4 runtime libraries
python34-libs.x86_64 : Python 3.4 runtime libraries
python34-pip.noarch : A tool for installing and managing Python packages
python34-setuptools.noarch : Easily build and distribute Python packages
python34-test.x86_64 : The test modules from the main python 3.4 package
python34-tools.x86_64 : A collection of tools included with Python 3.4
python34-virtualenv.noarch : Tool to create isolated Python environments
```

**Comment by aarcro** [comment]
I had luck building a python3.6 zappa lambda with lambci/lambda:build-python3.6 didn't need to install anything else to get my requirements to build.

**Comment by danielwhatmuff** [comment]
@peregrinius @avish-3pg @iMerica FYI I've just published `danielwhatmuff/zappa:python3.6`

**Comment by danielwhatmuff** [comment]
Code changes pushed to https://github.com/danielwhatmuff/zappa/tree/feature/python3.6
