### ISSUE TITLE
Error during build - pg_config executable not found

### ISSUE THREAD

**Issue by avish-3pg** [danielwhatmuff/zappa#6]
Collecting Django==1.10.7 (from -r requirements/base.txt (line 2))
  Downloading Django-1.10.7-py2.py3-none-any.whl (6.8MB)
Collecting django-configurations==2.0 (from -r requirements/base.txt (line 5))
  Downloading django_configurations-2.0-py2.py3-none-any.whl
Collecting psycopg2==2.7.1 (from -r requirements/base.txt (line 8))
  Downloading psycopg2-2.7.1.tar.gz (421kB)

    **Error: pg_config executable not found.**

    Please add the directory containing pg_config to the PATH or specify the full executable path with the option: python setup.py build_ext --pg-config /path/to/pg_config build ...or with the pg_config option in 'setup.cfg'. Complete output from command python setup.py egg_info:
    running egg_info    
    creating pip-egg-info/psycopg2.egg-info    
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO    
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt    
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt    
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'    
    warning: manifest_maker: standard file '-c' not found
    
    **Error: pg_config executable not found.**

Please add the directory containing pg_config to the PATH or specify the full executable path with the option: python setup.py build_ext --pg-config /path/to/pg_config build ...or with the pg_config option in 'setup.cfg'.

**Comment by avish-3pg** [comment]
@danielwhatmuff any insights on this issue will be helpful, thank you.

**Comment by danielwhatmuff** [comment]
Hi @avish-3pg. You may have to yum install postgresql-devel to your local image. You can use the Dockerfile.update for that. Sorry for the late reply.
