### ISSUE TITLE
Failure when building the image with a clone

### ISSUE THREAD

**Issue by michikhi** [danielwhatmuff/zappa#8]
Hi Daniel,

I am struggling with the first command to build the image: 
`git clone git@github.com:danielwhatmuff/zappa.git && cd zappa && docker build -t danielwhatmuff/zappa .`

Everything seems working well until I get this error message:
> Running transaction check
> Running transaction test
> Transaction test succeeded
> Running transaction
>   Installing : mysql55-libs-5.5.46-1.10.amzn1.x86_64                       1/23 
>   Installing : libgfortran-4.8.3-9.109.amzn1.x86_64                        2/23 
>   Installing : blas-3.5.0-8.6.amzn1.x86_64                                 3/23 
>   Installing : postgresql92-libs-9.2.15-1.57.amzn1.x86_64                  4/23 
>   Installing : postgresql92-9.2.15-1.57.amzn1.x86_64                       5/23 
>   Installing : blas-devel-3.5.0-8.6.amzn1.x86_64                           6/23 
>   Installing : lapack-3.5.0-8.6.amzn1.x86_64                               7/23 
>   Installing : gpm-libs-1.20.6-12.8.amzn1.x86_64                           8/23 
>   Installing : mysql-config-5.5.46-1.10.amzn1.x86_64                       9/23 
>   Installing : mysql55-5.5.46-1.10.amzn1.x86_64                           10/23 
>   Installing : mysql55-devel-5.5.46-1.10.amzn1.x86_64                     11/23 
>   Installing : libyaml-0.1.6-6.7.amzn1.x86_64                             12/23 
>   Installing : python27-pip-6.1.1-1.21.amzn1.noarch                       13/23 
>   Installing : ruby20-libs-2.0.0.648-1.29.amzn1.x86_64                    14/23 
>   Installing : 2:vim-filesystem-7.4.1416-1.37.amzn1.x86_64                15/23 
>   Installing : 2:vim-common-7.4.1416-1.37.amzn1.x86_64                    16/23 
>   Installing : 2:vim-enhanced-7.4.1416-1.37.amzn1.x86_64                  17/23 
>   Installing : python27-virtualenv-12.0.7-1.12.amzn1.noarch               18/23 
>   Installing : libyaml-devel-0.1.6-6.7.amzn1.x86_64                       19/23 
>   Installing : mysql-devel-5.5-1.6.amzn1.noarch                           20/23 
>   Installing : mysql-5.5-1.6.amzn1.noarch                                 21/23 
>   Installing : lapack-devel-3.5.0-8.6.amzn1.x86_64                        22/23 
>   Installing : postgresql92-devel-9.2.15-1.57.amzn1.x86_64                23/23
> 
> **Rpmdb checksum is invalid: dCDPT(pkg checksums): postgresql92-devel.x86_64 0:9.2.15-1.57.amzn1 - u**
>  
> The command '/bin/sh -c yum clean all &&     yum -y install python27-devel python27-virtualenv vim postgresql postgresql-devel mysql mysql-devel gcc lapack-devel blas-devel libyaml-devel &&     yum --enablerepo=epel -y install hdf5-devel &&     pip install -U pip &&     pip install -U zappa mysql-python' returned a non-zero code: 1

Did you ever faced that issue ?

Thanks in advance

**Comment by nicolastrres** [comment]
Hello, I am facing the same problem while building the image from the cloned Dockerfile

**Comment by danielwhatmuff** [comment]
@nicolastrres @michikhi  - I think the issue is with a package in an upstream yum repo. Might be worth trying to add `rpm --rebuilddb` before / after the yum installs in the Dockerfile.
